### ISSUE TITLE
Bug: retrying in game subtracts monkey money, can lead to negative values.

### ISSUE THREAD

**Issue by thatanti360** [doombubbles/retry-anywhere#1]
Everytime I press the retry button on the game over screen, it does what it's supposed to but after beating the level (or going to home), 100 monkey money is subtracted. I even got negative values on it.
![339894629_881331132963641_4019624987687263644_n](https://user-images.githubusercontent.com/81679933/230445108-0b1fc219-5301-4ae4-bfa0-62c8e9924269.jpg)
I'm using Melon Loader v0.6.1, the newest version of Mod Helper, and BTD6 is at version 36.0. This wasn't happening before this update.

**Comment by doombubbles** [comment]
This is actually a bug in the base game apparently LOL
![message from sav](https://media.discordapp.net/attachments/1093010712986656868/1093271821618520194/image0.jpg)

**Comment by thatanti360** [comment]
LOL I didn't know that. It makes sense, this button is the same as the one in challenge editor.
Thanks, I gotta check the NK discord more often, especially after major updates like this one.
